project:
  type: website
  output-dir: docs

website:
  #title: "Doan Nam Long Vu"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: publication.qmd
        text: Publications

format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true



