---
title: "About"
---

Doan Nam Long Vu (Vũ Đoàn Nam Long) finished his Master and Bachelor degree at Technical University of Darmstadt. He did B.Sc. research with [Prof. Steffen Eger](https://nl2g.github.io/team#Steffen_Eger) and [Dr. Nafise Sadat Moosavi](https://ns-moosavi.github.io/), M.Sc. research with [Prof. Yufang Hou](https://yufanghou.github.io/) and [Prof. Ivan Habernal](https://www.trusthlt.org/) at TU Darmstadt.

## Research Interest

Natural Language Processing: *Affective Computing, Machine Translation, Information Retrieval, Evaluation Metrics for Text Generation*

Privacy Preserving Techniques: *Differential Privacy, Cryptographic Protocol*

Applicaton: *Mental Health*

## Teaching

**Teaching Assistant**\
*[Foundation of Language Technology](https://www.informatik.tu-darmstadt.de/ukp/teaching_ukp/ukp_teaching_courses/ukp_courses_ws_20_3/index.en.jsp)*\
Winter Term 2022 and 2023\
at Technical University of Darmstadt

*[Deep Learning for Natural Language Processing](https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures)*\
Summer Term 2023\
at Technical University of Darmstadt


## Hobbies and other interests

In my free time, I enjoy doing street workout and swimming in the summer. And in winter, I have a ton of fun practicing bass guitar! 
I am also interested in Music Source Separation, mainly to extract the bass guitar stem for better music transcription.
Besides that, I also like to experience Virtual/Augmented Reality games/softwares.